### ISSUE TITLE
Verbindungsprobleme WiFi

### ISSUE THREAD

**Issue by reifab** [biit-hub/WIO-Terminal-IoTB-Template#1]
Das Wio Terminal kann sich oft nicht mit dem WLAN verbinden. Besonders häufig ist dieses Verhalten direkt nach dem Download. Wenn es fehlschlägt, verharrt der Code in der do- While Schleife in wio_wifi.cpp.

Ausgaben über UART (Serial Monitor):
    init Display
    init WiFi
    IoTB
    WiFi interface ready
    WiFi interface ready
    WiFi client started
    Disconnected from WiFi access point
    6 
    6
    6
    6

6 steht dabei für WL_DSICONNECTED

Allenfalls lässt sich das Problem lösen, wenn man in der do- While- Schleife einen reconnect() einbaut? Etwa so:

  do{
    //(*cbWiFiLog)("- Connecting...", false);   // write to the log
    delay(2000);
    Serial.println(WiFi.status());          // print to SerialPort
    WiFi.reconnect();
  } while (WiFi.status() != WL_CONNECTED);  // do until connected

**Comment by biit-hub** [comment]
Die Wiederverbindung beim Verlust der WiFi Verbindung wurde implementiert
