### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by reifab** [biit-hub/WIO-Terminal-IoTB-Template#6]
Wäre es möglich, den Warnungen, die beim Kompilieren auftauchen, auf den Grund zu gehen?

**Comment by biit-hub** [comment]
Die Warnung "suggest parentheses around assignment used as truth value [-Wparentheses]" wurde gelöst. Es war ein bug in einem if.

**Comment by biit-hub** [comment]
Die Warnung "array subscript is above array bounds [-Warray-bounds]" tritt auf, weil das Array "topicList" leer ist.
In der Vorlage wird nun ein String/Topic hinzugefügt, mit dem Komentar, dass dieses Beispiel gelöst werden soll, wenn eigene Topics in das Array geschrieben werden.

**Comment by biit-hub** [comment]
Die Warnung "ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]" konnte durch den Vorschlag von @reifab behoben werden.
