### ISSUE TITLE
Inkonsistenz bei der Auswahl der Zeile in Pages

### ISSUE THREAD

**Issue by reifab** [biit-hub/WIO-Terminal-IoTB-Template#7]
Könnte man die Indizes für die Zeile nicht konsistent gleich machen? Unten im Beispiel muss ich für das Setzen z.B. Index 0 nehmen, für das Updaten aber Index 1: 
![image](https://user-images.githubusercontent.com/72970313/154937223-a56a21d4-d094-46a5-a2dc-6b31ebd7de2f.png)

**Comment by reifab** [comment]
Die Änderungen haben folgenden neuen Bug verursacht: Wenn Line 0 überschrieben und aktualisiert (updateLine) wird wird, erscheint die Zahl eine Zeile über der erwarteten Position.
 pages_array[1].lines[0].value = 612;
 wio_disp.updateLine(pages_array[1],0,ONLY_VALUE);
 
 ![20220303_122412](https://user-images.githubusercontent.com/72970313/156566486-aadbd1aa-2779-4bf1-aff1-d2437f0aaf61.jpg)

**Comment by biit-hub** [comment]
Habe den Bug behoben und die Kommentare angepasst
